language: elixir
elixir:
  - 1.7.3
  - 1.6.5
otp_release: 21.0
env:
  - MIX_ENV=test
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
jobs:
  include:
  - stage: test
    script: mix autoformatbot
    elixir: 1.7.3
    branches:
      only: master
